app/finalapp/auth.py
# """Routes for user authentication."""
# from flask import Blueprint, redirect, render_template, flash, request, session, url_for
# from flask_login import login_required, logout_user, current_user, login_user
# from .forms import LoginForm, SignupForm
# from .models import db, User
# from . import login_manager
# from flask_login import current_user, login_user
#
# # Blueprint Configuration
# auth_bp = Blueprint(
#     'auth_bp', __name__,
#     template_folder='templates',
#     static_folder='static'
# )
#
#
# @auth_bp.route('/login', methods=['GET', 'POST'])
# def login():
#     """
#        Log-in page for registered users.
#        GET requests serve Log-in page.
#        POST requests validate and redirect user to dashboard.
#        """
#     # Bypass if user is logged in
#     if current_user.is_authenticated:
#         return redirect(url_for('main_bp.dashboard'))
#
#     form = LoginForm()
#     # Validate login attempt
#     if form.validate_on_submit():
#         user = User.query.filter_by(email=form.email.data).first()
#         if user and user.check_password(password=form.password.data):
#             login_user(user)
#             next_page = request.args.get('next')
#             return redirect(next_page or url_for('main_bp.dashboard'))
#         flash('Invalid username/password combination')
#         return redirect(url_for('auth_bp.login'))
#     return render_template(
#         'login.jinja2',
#         form=form,
#         title='Log in.',
#         template='login-page',
#         body="Log in with your User account."
#     )
#
#
# @auth_bp.route('/signup', methods=['GET', 'POST'])
# def signup():
#     """
#        User sign-up page.
#
#        GET requests serve sign-up page.
#        POST requests validate form & user creation.
#        """
#     form = SignupForm()
#     if form.validate_on_submit():
#         existing_user = User.query.filter_by(email=form.email.data).first()
#         if existing_user is None:
#             user = User(
#                 name=form.name.data,
#                 email=form.email.data,
#                 website=form.website.data
#             )
#             user.set_password(form.password.data)
#             db.session.add(user)
#             db.session.commit()  # Create new user
#             login_user(user)  # Log in as newly created user
#             return redirect(url_for('main_bp.dashboard'))
#         flash('A user already exists with that email address.')
#     return render_template(
#         'signup.jinja2',
#         title='Create an Account.',
#         form=form,
#         template='signup-page',
#         body="Sign up for a user account."
#     )

"""Routes for user authentication."""
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user

from . import login_manager
from .forms import LoginForm, SignupForm
from .models import User, db

# Blueprint Configuration
auth_bp = Blueprint(
    'auth_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    """
    User sign-up page.

    GET requests serve sign-up page.
    POST requests validate form & user creation.
    """
    form = SignupForm()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user is None:
            user = User(
                name=form.name.data,
                email=form.email.data,
                website=form.website.data
            )
            user.set_password(form.password.data)
            db.session.add(user)
            db.session.commit()  # Create new user
            login_user(user)  # Log in as newly created user
            return redirect(url_for('main_bp.dashboard'))
        flash('A user already exists with that email address.')
    return render_template(
        'signup.jinja2',
        title='Create an Account.',
        form=form,
        template='signup-page',
        body="Sign up for a user account."
    )


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    """
    Log-in page for registered users.

    GET requests serve Log-in page.
    POST requests validate and redirect user to dashboard.
    """
    # Bypass if user is logged in
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.dashboard'))

    form = LoginForm()
    # Validate login attempt
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(password=form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page or url_for('main_bp.dashboard'))
        flash('Invalid username/password combination')
        return redirect(url_for('auth_bp.login'))
    return render_template(
        'login.jinja2',
        form=form,
        title='Log in.',
        template='login-page',
        body="Log in with your User account."
    )


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in upon page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash('You must be logged in to view that page.')
    return redirect(url_for('auth_bp.login'))

app/finalapp/routes.py
# """Routing."""
# from flask import current_app as app
# from flask import redirect, render_template, url_for
# from flask import make_response, redirect, render_template, request, url_for
# from .models import User, db
# from .forms import ContactForm, SignupForm
# from datetime import datetime as dt
# from flask import Blueprint, redirect, render_template, url_for
# from flask_login import current_user, login_required, logout_user
#
#
# main_bp = Blueprint(
#     'main_bp', __name__,
#     template_folder='templates',
#     static_folder='static'
# )
#
#
# # @app.route("/")
# # def home():
# #     """Landing page."""
# #     return render_template(
# #         "index.jinja2",
# #         template="home-template",
# #         title="Flask-WTF tutorial"
# #     )
#
#
# @app.route("/contact", methods=["GET", "POST"])
# def contact():
#     """Standard `contact` form."""
#     form = ContactForm()
#     if form.validate_on_submit():
#         return redirect(url_for("success"))
#     return render_template(
#         "contact.jinja2",
#         form=form,
#         template="form-template",
#         title="Contact Form"
#     )
#
#
# @app.route("/signup", methods=["GET", "POST"])
# def signup():
#     """User sign-up form for account creation."""
#     form = SignupForm()
#     if form.validate_on_submit():
#         return redirect(url_for("success"))
#     return render_template(
#         "signup.jinja2",
#         form=form,
#         template="form-template",
#         title="Signup Form"
#     )
#
#
# @app.route("/success", methods=["GET", "POST"])
# def success():
#     """Generic success page upon form submission."""
#     return render_template(
#         "success.jinja2",
#         template="success-template"
#     )
#
# @app.route("/user", methods=["GET"])
# def user_records():
#     """Create a user via query string parameters."""
#     username = request.args.get("user")
#     email = request.args.get("email")
#     if username and email:
#         existing_user = User.query.filter(
#             User.username == username or User.email == email
#         ).first()
#         if existing_user:
#             return make_response(f"{username} ({email}) already created!")
#         new_user = User(
#             username=username,
#             email=email,
#             created=dt.now(),
#             bio="In West Philadelphia born and raised, \
#             on the playground is where I spent most of my days",
#             admin=False,
#         )  # Create an instance of the User class
#         db.session.add(new_user)  # Adds new User record to database
#         db.session.commit()  # Commits all changes
#         redirect(url_for("user_records"))
#     return render_template("users.jinja2", users=User.query.all(), title="Show Users")
#
# @app.route('/getUsers', methods=['GET'])
# def create_user():
#     """Create a user."""
#     ...
#     return render_template(
#         'users.jinja2',
#         users=User.query.all(),
#         title="Show Users"
#     )
#
# @main_bp.route('/', methods=['GET'])
# @login_required
# def dashboard():
#     """Logged-in User Dashboard."""
#     return render_template(
#         'dashboard.jinja2',
#         title='Flask-Login Tutorial.',
#         template='dashboard-template',
#         current_user=current_user,
#         body="You are now logged in!"
#     )
#
#
# @main_bp.route("/logout")
# @login_required
# def logout():
#     """User log-out logic."""
#     logout_user()
#     return redirect(url_for('auth_bp.login'))

"""Logged-in page routes."""
from flask import Blueprint, redirect, render_template, url_for
from flask_login import current_user, login_required, logout_user

# Blueprint Configuration
main_bp = Blueprint(
    'main_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


@main_bp.route('/', methods=['GET'])
@login_required
def dashboard():
    """Logged-in User Dashboard."""
    return render_template(
        'dashboard.jinja2',
        title='Flask-Login Tutorial.',
        template='dashboard-template',
        current_user=current_user,
        body="You are now logged in!"
    )


@main_bp.route("/logout")
@login_required
def logout():
    """User log-out logic."""
    logout_user()
    return redirect(url_for('auth_bp.login'))

app/finalapp/templates/contact.jinja2
{% extends 'layout.jinja2' %}

{% block styles %}
    <link
            rel="stylesheet"
            href="{{ url_for('static', filename='css/forms.css') }}"
            type="text/css"
    />
{% endblock %}

{% block content %}

    <div class="form-wrapper">
      <h2 class="title">Contact</h2>
      <form method="POST" action="{{ url_for('contact') }}">
        {{ form.csrf_token }}

        <fieldset class="form-field">{{ form.name.label }} {{ form.name(size=20) }}
          {% if form.name.errors %}
            <ul class="errors">
                {% for error in form.email.errors %}
                  <li class="error">
                      <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                  </li>
                {% endfor %}
              </ul>
          {% endif %}
        </fieldset>

        <fieldset class="form-field">{{ form.email.label }} {{ form.email }}
          {% if form.email.errors %}
            <ul class="errors">
                {% for error in form.email.errors %}
                  <li class="error">
                      <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                  </li>
                {% endfor %}
              </ul>
          {% endif %}
        </fieldset>

        <fieldset class="form-field">{{ form.body.label }} {{ form.body }}
          {% if form.body.errors %}
            <ul class="errors">
                {% for error in form.email.errors %}
                  <li class="error">
                      <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                  </li>
                {% endfor %}
              </ul>
          {% endif %}
        </fieldset>

        {{ form.submit }}
      </form>
    </div>

{% endblock %}

app/finalapp/templates/dashboard.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/dashboard.css') }}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}

{% block content %}
  <h1>{{ body }}</h1>

  {% if current_user.is_authenticated %}
    <p>Hi {{ current_user.name }}!</p>
    <a href="{{ url_for('main_bp.logout') }}">Log out</a>
  {% endif %}

{% endblock %}

app/finalapp/templates/home.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <h1>{{title}}</h1>
        <p>{{description}}</p>
    </div>
{% endblock %}

app/finalapp/templates/index.jinja2
{% extends 'layout.jinja2' %}

{% block styles %}

    <link
        rel="stylesheet"
        href="{{ url_for('static', filename='css/home.css') }}"
        type="text/css"
    />

{% endblock %}


{% block content %}

    <h1>Flask-WTF Tutorial</h1>
    <ul>
      <li>
          <a href="{{ url_for('contact') }}">
              Contact Form <i class="fas fa-chevron-right"></i>
          </a>
      </li>
      <li>
          <a href="{{ url_for('signup') }}">
              Signup Form <i class="fas fa-chevron-right"></i>
          </a>
      </li>
    </ul>

{% endblock %}

app/finalapp/templates/layout.html
<!doctype html>
<html>

  <head>
    <title>{{title}}</title>
    <meta charset="utf-8">
    <meta name="description" content={{description}}>
    <link rel="shortcut icon" href="/favicon.ico">
    {% block css %}{% endblock %}
  </head>

  <body>
    {% include 'navigation.html' %}
    {% block content %}{% endblock %}
  </body>

</html>

app/finalapp/templates/layout.jinja2
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>{{ title }} - Hackers and Slackers</title>
    <meta name="HandheldFriendly" content="True"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
    <meta name="theme-color" content="#5eb9d7" >
    <link rel="canonical" href="https://flaskwtf.hackersandslackers.app/" />
    <link rel="shortcut icon" href="{{ url_for('static', filename='dist/img/favicon.png') }}" type="image/x-icon"/>

    {# OpenGraph #}
    <meta property="og:site_name" content={{ title }} />
    <meta property="og:type" content="website" />
    <meta property="og:title" content={{ title }} />
    <meta property="og:description" content={{ description }} />
    <meta property="og:url" content="https://flaskwtf.hackersandslackers.app/" />
    <meta property="og:image" content="/.github/flask-wtforms-tutorial@2x.jpg" />
    <meta property="og:image:width" content="1000" />
    <meta property="og:image:height" content="523" />

    {# Styles #}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
    <script src="https://kit.fontawesome.com/e3deaeba31.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,500" rel="stylesheet">
    {% block styles %}{% endblock %}
</head>

<body class="{{ template }}">

<div class="container">
    {% block content %}{% endblock %}
</div>

<script type="text/javascript">
    var _gauges = _gauges || [];
    (function () {
        var t = document.createElement('script');
        t.type = 'text/javascript';
        t.async = true;
        t.id = 'gauges-tracker';
        t.setAttribute('data-site-id', '5eb6bab25292fb79acffe181');
        t.setAttribute('data-track-path', 'https://track.gaug.es/track.gif');
        t.src = 'https://d2fuc4clr7gvcn.cloudfront.net/track.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(t, s);
    })();
</script>

</body>

</html>

app/finalapp/templates/login.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/account.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
  <div class="form-wrapper">

    <div class="logo">
      <img src="{{ url_for('static', filename='dist/img/logo.png') }}" alt="logo"/>
    </div>

    {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
      </div>
    {% endfor %}

    <h1>Log In</h1>

    <form method="POST" action="/login">
      {{ form.csrf_token }}

      <fieldset class="email">
        {{ form.email.label }}
        {{ form.email(placeholder='youremail@example.com') }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.email.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="password">
        {{ form.password.label }}
        {{ form.password }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.password.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <div class="submit-button">
        {{ form.submit }}
      </div>

      <div class="login-signup">
        <span>Don't have an account? <a href="{{ url_for('auth_bp.signup') }}">Sign up.</a></span>
      </div>

    </form>
  </div>
{% endblock %}

app/finalapp/templates/navigation.html
<header>
   <nav>
    {% for link in nav %}
      <a href="{{ link.url }}">{{ link.name }}</a>
    {% endfor %}
  </nav>
</header>

app/finalapp/templates/signup.jinja2
{% extends 'layout.jinja2' %}

{% block styles %}

    <link
        rel="stylesheet"
        href="{{ url_for('static', filename='css/forms.css') }}"
        type="text/css"
    />

{% endblock %}

{% block content %}

    <div class="form-wrapper">
      <h2 class="title">Sign Up</h2>

      <form method="POST" action="{{ url_for('signup') }}">
          {{ form.csrf_token }}

          <fieldset class="form-field">{{ form.email.label }} {{ form.email }}
            {% if form.email.errors %}
              <ul class="errors">
                {% for error in form.email.errors %}
                  <li class="error">
                      <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                  </li>
                {% endfor %}
              </ul>
            {% endif %}
          </fieldset>

          <fieldset class="form-field">{{ form.password.label }} {{ form.password }}
            {% if form.password.errors %}
              <ul class="errors">
                {% for error in form.email.errors %}
                  <li class="error">
                      <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                  </li>
                {% endfor %}
              </ul>
            {% endif %}
          </fieldset>

          <fieldset class="form-field">{{ form.confirmPassword.label }} {{ form.confirmPassword }}
            {% if form.confirmPassword.errors %}
              <ul class="errors">
                {% for error in form.email.errors %}
                  <li class="error">
                      <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                  </li>
                {% endfor %}
              </ul>
            {% endif %}
          </fieldset>

          <fieldset class="form-field">{{ form.title.label }} {{ form.title }}
            <i class="fas fa-caret-down"></i>
            {% if form.title.errors %}
              <ul class="errors">
                {% for error in form.email.errors %}
                  <li class="error">
                      <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                  </li>
                {% endfor %}
              </ul>
            {% endif %}
          </fieldset>

          <fieldset class="form-field">{{ form.website.label }} {{ form.website }}
            {% if form.website.errors %}
              <ul class="errors">
                {% for error in form.email.errors %}
                  <li class="error">
                      <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                  </li>
                {% endfor %}
              </ul>
            {% endif %}
          </fieldset>

          <fieldset class="form-field">{{ form.birthday.label }} {{ form.birthday }}
            {% if form.birthday.errors %}
              <ul class="errors">
                {% for error in form.email.errors %}
                  <li class="error">
                      <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                  </li>
                {% endfor %}
              </ul>
            {% endif %}
          </fieldset>

          {{ form.recaptcha }}
          {{ form.submit }}

      </form>
    </div>

{% endblock %}

app/finalapp/templates/success.jinja2
{% extends 'layout.jinja2' %}

{% block styles %}

    <link
        rel="stylesheet"
        href="{{ url_for('static', filename='css/success.css') }}"
        type="text/css"
    />

{% endblock %}

{% block content %}

    <div class="success-wrapper">
      <h1>SUCCESS!</h1>
      <p>You've submitted a valid form. Your mother would be proud.</p>
      <a href="{{ url_for('home') }}">
          <button>Start over</button>
      </a>
    </div>

{% endblock %}

app/finalapp/templates/users.jinja2
{% extends "layout.jinja2" %}

{% block content %}
  <div class="container">
    <h1>Flask-SQLAlchemy Tutorial</h1>
    {% for user in users %}
      <ul id="user.username">
        <li>
          <span class="field-name">User:</span>
          <span class="field-value">{{ user.username }}</span>
        </li>
        <li>
          <span class="field-name">Email:</span>
          <span class="field-value">{{ user.email }}</span>
        </li>
        <li>
          <span class="field-name">Created:</span>
          <span class="field-value">{{ user.created }}</span>
        </li>
        <li>
          <span class="field-name">Bio:</span>
          <span class="field-value">{{ user.bio }}</span>
        </li>
        <li>
          <span class="field-name">Admin:</span>
          <span class="field-value">{{ user.admin }}</span>
        </li>
      </ul>
    {% endfor %}
  </div>
{% endblock %}
© 2021 Git